### ISSUE TITLE
Больше причёсок и бород. 

### ISSUE THREAD

**Issue by Shararashik** [PepsiBay/PepsiBay12#13]
_По коробу поскреби, по сусеку помети; авось спрайтов и наберется_
Ну, тут всё просто, на ониксе есть причёски, которых нет на пепсибее. Как пример - ladylike и ladylike alt. Также можно полазить по билдам и повытаскивать всякие причёски и оттуда. Я говорю конечно не только о трапских, а вообще о всех, бороды и усы в этот список тоже входят. 
https://i.imgur.com/UdiJkhl.jpg

**Comment by yura-pepsicola** [comment]
со спрайтами та ещё жопа, ну ладно будет
